# =============================================================================
# PDFAutomation.py
# Author  : Pavan Shetty H S
# Date    : August 2024
# Topic   : PDF Generation and Manipulation
# =============================================================================
#
# Notes from Pavan:
# Used reportlab for generating PDFs from scratch (like reports) and
# PyPDF2/pypdf for manipulating EXISTING PDFs (merging, splitting,
# extracting text). Two different libraries for two different jobs --
# took me a confused afternoon before I understood reportlab CREATES,
# pypdf MANIPULATES existing files.
# =============================================================================

import os

print("=" * 50)
print("    PDF AUTOMATION DEMO")
print("=" * 50)

# ---------------------
# Generating a PDF from scratch with reportlab
# ---------------------
print("\n[1] Generating a PDF report from scratch (reportlab)")

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib import colors

def generate_expense_report(filename, expenses, total):
    """Generates a simple PDF expense report.
    This exact function is what powers the PDF export feature in my
    Expense Tracker project (Project 5)."""
    c = canvas.Canvas(filename, pagesize=A4)
    width, height = A4

    # Title
    c.setFont("Helvetica-Bold", 18)
    c.drawString(1*inch, height - 1*inch, "Monthly Expense Report")

    c.setFont("Helvetica", 10)
    c.drawString(1*inch, height - 1.3*inch, "Generated by Pavan Shetty H S's Expense Tracker")

    # Table header
    y_position = height - 2*inch
    c.setFont("Helvetica-Bold", 12)
    c.drawString(1*inch, y_position, "Category")
    c.drawString(3.5*inch, y_position, "Description")
    c.drawString(6*inch, y_position, "Amount")

    c.line(1*inch, y_position - 0.1*inch, 7*inch, y_position - 0.1*inch)

    # Table rows
    c.setFont("Helvetica", 10)
    y_position -= 0.4*inch
    for category, description, amount in expenses:
        c.drawString(1*inch, y_position, category)
        c.drawString(3.5*inch, y_position, description)
        c.drawString(6*inch, y_position, f"Rs.{amount:.2f}")
        y_position -= 0.3*inch

    # Total
    c.setFont("Helvetica-Bold", 12)
    c.line(1*inch, y_position - 0.05*inch, 7*inch, y_position - 0.05*inch)
    y_position -= 0.3*inch
    c.drawString(5*inch, y_position, f"Total: Rs.{total:.2f}")

    c.save()
    print(f"  PDF generated: {filename}")

sample_expenses = [
    ("Food", "Groceries", 2500.00),
    ("Transport", "Fuel", 1800.00),
    ("Bills", "Electricity", 1200.00),
    ("Education", "Online Course", 999.00),
]
total_amount = sum(e[2] for e in sample_expenses)

generate_expense_report("sample_report.pdf", sample_expenses, total_amount)

# ---------------------
# Reading text from an existing PDF
# ---------------------
print("\n[2] Reading text from a PDF (pypdf)")
from pypdf import PdfReader

reader = PdfReader("sample_report.pdf")
print(f"  Number of pages: {len(reader.pages)}")
first_page_text = reader.pages[0].extract_text()
print(f"  Extracted text (first 100 chars): {first_page_text[:100]}...")

# ---------------------
# Merging multiple PDFs
# ---------------------
print("\n[3] Merging multiple PDFs (pypdf)")
from pypdf import PdfWriter

# Generate a second sample PDF to merge
generate_expense_report("sample_report2.pdf", sample_expenses, total_amount)

writer = PdfWriter()
for pdf_file in ["sample_report.pdf", "sample_report2.pdf"]:
    reader = PdfReader(pdf_file)
    for page in reader.pages:
        writer.add_page(page)

with open("merged_report.pdf", "wb") as f:
    writer.write(f)
print("  Merged 2 PDFs into merged_report.pdf")

merged_reader = PdfReader("merged_report.pdf")
print(f"  Merged PDF has {len(merged_reader.pages)} pages total")

# ---------------------
# Adding a watermark / metadata
# ---------------------
print("\n[4] Adding metadata to a PDF")
writer2 = PdfWriter()
reader2 = PdfReader("sample_report.pdf")
for page in reader2.pages:
    writer2.add_page(page)

writer2.add_metadata({
    "/Title": "Monthly Expense Report",
    "/Author": "Pavan Shetty H S",
    "/Subject": "Personal Finance Tracking"
})

with open("report_with_metadata.pdf", "wb") as f:
    writer2.write(f)
print("  Added metadata (Title, Author, Subject) to PDF")

# ---------------------
# Splitting a PDF into individual pages
# ---------------------
print("\n[5] Splitting a PDF into separate page files")
merged_reader2 = PdfReader("merged_report.pdf")
for i, page in enumerate(merged_reader2.pages):
    split_writer = PdfWriter()
    split_writer.add_page(page)
    split_filename = f"split_page_{i+1}.pdf"
    with open(split_filename, "wb") as f:
        split_writer.write(f)
    print(f"  Created {split_filename}")

# Cleanup all generated demo files
demo_files = ["sample_report.pdf", "sample_report2.pdf", "merged_report.pdf",
              "report_with_metadata.pdf", "split_page_1.pdf", "split_page_2.pdf"]
for f in demo_files:
    if os.path.exists(f):
        os.remove(f)
print(f"\n  Cleanup: removed {len(demo_files)} demo PDF files")

print("\n" + "=" * 50)

# =============================================================================
# Debugging note: Confused reportlab's coordinate system at first --
# (0,0) is BOTTOM-LEFT of the page, not top-left like screen/image
# coordinates I was used to. Spent a while wondering why my "header"
# text kept appearing at the bottom of the page until I realized I
# needed height - some_value instead of just some_value for y position.
# =============================================================================

# =============================================================================
# PROGRAM OUTPUT
# Run with: python3 PDFAutomation.py
# =============================================================================
#
# ==================================================
#     PDF AUTOMATION DEMO
# ==================================================
#
# [1] Generating a PDF report from scratch (reportlab)
#   PDF generated: sample_report.pdf
#
# [2] Reading text from a PDF (pypdf)
#   Number of pages: 1
#   Extracted text (first 100 chars): Monthly Expense Report
# Generated by Pavan Shetty H S's Expense Tracker
# Category
# Description
# Amount
# F...
#
# [3] Merging multiple PDFs (pypdf)
#   PDF generated: sample_report2.pdf
#   Merged 2 PDFs into merged_report.pdf
#   Merged PDF has 2 pages total
#
# [4] Adding metadata to a PDF
#   Added metadata (Title, Author, Subject) to PDF
#
# [5] Splitting a PDF into separate page files
#   Created split_page_1.pdf
#   Created split_page_2.pdf
#
#   Cleanup: removed 6 demo PDF files
#
# ==================================================
#
# =============================================================================

